var allTestFiles = [];
var TEST_REGEXP = /(spec|test)\.js$/i;

var pathToModule = function(path) {
  return path.replace(/^\/base\//, '').replace(/\.js$/, '');
};

Object.keys(window.__karma__.files).forEach(function(file) {
  if (TEST_REGEXP.test(file)) {
    // Normalize paths to RequireJS module names.
    allTestFiles.push(pathToModule(file));
  }
});

// Start of RequireJS Config, generated by Grunt!
var requirejsConfig = {"baseUrl":"./","paths":{"text":"lib/vendor/requirejs-text/text","angular":"lib/vendor/angular/angular.min","jquery":"lib/vendor/jquery/dist/jquery.min","bootstrap":"lib/vendor/bootstrap/dist/js/bootstrap.min","uiBootstrap":"lib/vendor/angular-bootstrap/ui-bootstrap-tpls.min","uiRouter":"lib/vendor/angular-ui-router/release/angular-ui-router.min","lodash":"lib/vendor/lodash/dist/lodash.min","ngMocks":"lib/vendor/angular-mocks/angular-mocks","appConf":"etc/app.conf","appRoutes":"etc/routes.conf"},"packages":[{"name":"AppPkg","location":"src/js/App"},{"name":"CososPkg","location":"src/js/Cosos"}],"shim":{"angular":{"exports":"angular"},"uiBootstrap":{"deps":["angular"]},"jquery":{"exports":"jQuery"},"bootstrap":{"deps":["jquery"]},"uiRouter":{"deps":["angular"]},"lodash":{"exports":"_"},"ngMocks":{"deps":["angular"]},"restangular":{"deps":["angular","lodash"]}}};
// End of RequireJS Config, generated by Grunt!

requirejsConfig.baseUrl = '/base';
requirejsConfig.deps = allTestFiles; // dynamically load all test files
requirejsConfig.callback = window.__karma__.start; // we have to kickoff jasmine, as it is asynchronous
require.config(requirejsConfig);